### ISSUE TITLE
error: Illegal value for `line`

### ISSUE THREAD

**Issue by demeoni** [dqisme/vscode-sync-scroll#38]
error: Illegal value for `line`

this come up on lastest vscode update.
Vscode version:
Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee

<img width="299" alt="err" src="https://user-images.githubusercontent.com/5569720/236646604-8cee74a1-a536-43ca-906e-bf8286cbf931.png">

**Comment by jtsom** [comment]
Same here. More details:
```
mainThreadExtensionService.ts:81 [dqisme.sync-scroll]Illegal value for `line`
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:862
deliver @ event.ts:1075
fire @ event.ts:1031
fire @ ipc.net.ts:650
Y.onmessage @ localProcessExtensionHost.ts:583
mainThreadExtensionService.ts:82 Error: Illegal value for `line`
	at m.t (c:\Users\jtsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:961)
	at Object.lineAt (c:\Users\jtsombakos\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:90)
	at countLengthOfLineAt (c:\Users\jtsombakos\.vscode-insiders\extensions\dqisme.sync-scroll-1.3.1\out\utils.js:5:77)
	at calculateCharacterNumber (c:\Users\jtsombakos\.vscode-insiders\extensions\dqisme.sync-scroll-1.3.1\out\utils.js:7:83)
	at exports.calculatePosition (c:\Users\jtsombakos\.vscode-insiders\extensions\dqisme.sync-scroll-1.3.1\out\utils.js:9:132)
	at exports.calculateRange (c:\Users\jtsombakos\.vscode-insiders\extensions\dqisme.sync-scroll-1.3.1\out\utils.js:10:107)
	at c:\Users\jtsombakos\.vscode-insiders\extensions\dqisme.sync-scroll-1.3.1\out\extension.js:75:52
	at Array.forEach (<anonymous>)
	at Timeout._onTimeout (c:\Users\jtsombakos\.vscode-insiders\extensions\dqisme.sync-scroll-1.3.1\out\extension.js:73:18)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
```
